-- Bootstrap Environment
-- Bootstrapping consists of setting up the minimum configuration to allow
-- an automated script to build an environment.
--
-- DO NOT RUN THIS SCRIPT IN AN ALREADY PROVISIONED ENVIROMENT
--
USE ROLE ACCOUNTADMIN;

-- Set the desired timezone
ALTER ACCOUNT SET TIMESTAMP_TYPE_MAPPING = timestamp_ntz;
ALTER ACCOUNT SET TIMEZONE = 'UTC';

-- Create Warehouses
CREATE WAREHOUSE GDA_WH_L WITH 
    WAREHOUSE_SIZE = Large
    MAX_CLUSTER_COUNT = 2
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE GDA_WH_M WITH 
    WAREHOUSE_SIZE = Medium
    MAX_CLUSTER_COUNT = 2
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE GDA_WH_S WITH 
    WAREHOUSE_SIZE = Small
    MAX_CLUSTER_COUNT = 2
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE GDA_WH_XL WITH 
    WAREHOUSE_SIZE = XLarge
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE GDA_WH_XS WITH 
    WAREHOUSE_SIZE = XSmall
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
 
CREATE WAREHOUSE GDA_WH_XXL WITH 
    WAREHOUSE_SIZE = XXLarge
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create service user: flyway
CREATE ROLE GDA_SERVICE COMMENT = 'Service role used by gda-database automation scripts';
GRANT ROLE GDA_SERVICE TO ROLE SYSADMIN;

GRANT CREATE ROLE ON ACCOUNT TO ROLE GDA_SERVICE;
GRANT CREATE USER ON ACCOUNT TO ROLE GDA_SERVICE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE GDA_SERVICE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE GDA_SERVICE;

-- Grant usage and operator on all warehouses.  This is necessary to allow WH grants to other objects.
-- That is if GDA_SERVICE doesn't have usage it can't grant usage to another object.
GRANT USAGE ON WAREHOUSE GDA_WH_XS TO ROLE GDA_SERVICE;
GRANT USAGE ON WAREHOUSE GDA_WH_S TO ROLE GDA_SERVICE;
GRANT USAGE ON WAREHOUSE GDA_WH_M TO ROLE GDA_SERVICE;
GRANT USAGE ON WAREHOUSE GDA_WH_L TO ROLE GDA_SERVICE;
GRANT USAGE ON WAREHOUSE GDA_WH_XL TO ROLE GDA_SERVICE;
GRANT USAGE ON WAREHOUSE GDA_WH_XXL TO ROLE GDA_SERVICE;

GRANT OPERATE ON WAREHOUSE GDA_WH_XS TO ROLE GDA_SERVICE;
GRANT OPERATE ON WAREHOUSE GDA_WH_S TO ROLE GDA_SERVICE;
GRANT OPERATE ON WAREHOUSE GDA_WH_M TO ROLE GDA_SERVICE;
GRANT OPERATE ON WAREHOUSE GDA_WH_L TO ROLE GDA_SERVICE;
GRANT OPERATE ON WAREHOUSE GDA_WH_XL TO ROLE GDA_SERVICE;
GRANT OPERATE ON WAREHOUSE GDA_WH_XXL TO ROLE GDA_SERVICE;

CREATE USER flyway PASSWORD=&{password} DEFAULT_ROLE = GDA_SERVICE;
GRANT ROLE GDA_SERVICE TO USER flyway;
